---
########################################################
# Install RD Session Hosts
########################################################

- name: Install RD Session Host Role
  hosts: rd_session_hosts
  gather_facts: true

  tasks:

    ####################################################
    # Install Session Host Features
    ####################################################

    - name: Install Session Host Features
      win_feature:
        name: "{{ rd_sessionhost_features }}"
        state: present
        include_management_tools: true

    ####################################################
    # Configure RDP Settings
    ####################################################

    - name: Enable Remote Desktop
      win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword

    ####################################################
    # Ensure RDP Service
    ####################################################

    - name: Ensure Remote Desktop Service
      win_service:
        name: TermService
        state: started

    ####################################################
    # Display Completion Message
    ####################################################

    - name: Display Session Host Completion
      debug:
        msg: "RD Session Host installation completed successfully."