---
########################################################
# RD Gateway Default Variables
########################################################

gateway_https_port: 443

gateway_allowed_ports:
  - 443
  - 3391