########################################################
# Global Variables
########################################################

environment: poc
project_name: rds-project

########################################################
# Domain Configuration
########################################################

domain_name: contoso.local
domain_netbios_name: CONTOSO

########################################################
# RDS Deployment Configuration
########################################################

rds_collection_name: RDS-Collection

########################################################
# Licensing Configuration
########################################################

rds_license_mode: PerUser

########################################################
# Timezone Configuration
########################################################

windows_timezone: "India Standard Time"

########################################################
# Windows Features
########################################################

common_windows_features:
  - NET-Framework-45-Features
  - RSAT
  - FS-FileServer

########################################################
# WinRM Configuration
########################################################

winrm_transport: ntlm

########################################################
# Security Configuration
########################################################

disable_ie_esc: true

########################################################
# Logging
########################################################

ansible_log_path: ./ansible.log