########################################################
# RD Broker Configuration
########################################################

rd_broker_role: true

########################################################
# Windows Features
########################################################

rd_broker_features:
  - RDS-Connection-Broker
  - RDS-Licensing
  - RSAT-RDS-Tools

########################################################
# Broker Settings
########################################################

broker_name: rdbroker01

########################################################
# Licensing
########################################################

license_server: rdbroker01

########################################################
# Licensing Mode
########################################################

license_mode: PerUser

########################################################
# SQL Configuration
########################################################

rds_sql_enabled: false