########################################################
# RD Gateway Configuration
########################################################

rd_gateway_role: true

########################################################
# Windows Features
########################################################

rd_gateway_features:
  - RDS-Gateway
  - RSAT-RDS-Gateway

########################################################
# Gateway Settings
########################################################

gateway_name: rdgw01

########################################################
# HTTPS Certificate
########################################################

gateway_certificate_thumbprint: ""

########################################################
# CAP Configuration
########################################################

gateway_cap_name: RD-CAP

########################################################
# RAP Configuration
########################################################

gateway_rap_name: RD-RAP

########################################################
# Firewall Rules
########################################################

gateway_allowed_ports:
  - 443
  - 3391