---
########################################################
# RD Broker Default Variables
########################################################

license_mode: PerUser

license_mode_value: 4