---
########################################################
# Restart Broker Server
########################################################

- name: Restart Broker Server
  win_reboot:
    reboot_timeout: 1800