---
########################################################
# Restart Session Host
########################################################

- name: Restart Session Host
  win_reboot:
    reboot_timeout: 1800